[project]
name = "intercom-streamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "opencv-python-headless>=4.12.0.88",
    "paho-mqtt>=2.1.0",
]
